# Generated by Django 5.0.7 on 2024-08-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_registered',
        ),
    ]
