# Generated by Django 5.0.7 on 2024-08-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_profile_is_registered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
