# Generated by Django 5.0.7 on 2024-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
